name: TRUPPE FLEDERMAUS
favicon: null
layout_spectrum: 0.81288
typography_spectrum: 0.90383
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: one hundred views of the drowning world and dreams from a drowning world
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000100'
    - '#878991'
    - '#383A53'
    - '#C6CFD8'
    - '#9A016F'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
