title: one hundred views of the drowning world and dreams from a drowning world
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#000100'
    - '#878991'
    - '#383A53'
    - '#C6CFD8'
    - '#9A016F'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: TRUPPE FLEDERMAUS
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.90383
layout_spectrum: 0.81288
